-- =========================================================
-- FarmTablet v2 - Bucket Tracker App (legacy stub)
-- Merged into ExcavatorApp. FT.APP.BUCKET redirects to
-- FT.APP.EXCAVATOR via AppRegistry.resolve / switchApp.
-- Bucket session state + counting live on FarmTabletSystem
-- and update every frame (off-page / tablet closed).
-- =========================================================
