-- =========================================================
-- FarmTablet v2 - Digging App (legacy stub)
-- Merged into ExcavatorApp. FT.APP.DIGGING redirects to
-- FT.APP.EXCAVATOR via AppRegistry.resolve / switchApp.
-- =========================================================
